// ====== 必备证件与单据词汇 ======
const essentialData = [
  { en: "License", cn: "驾照", pr: "/ˈlaɪsns/" },
  { en: "Registration", cn: "（车辆）注册", pr: "/ˌredʒɪˈstreɪʃən/" },
  { en: "CDL (Commercial Driver’s License)", cn: "商业驾驶执照", pr: "C-D-L" },
  { en: "Apportioned Registration Cab Card (IRP)", cn: "分摊注册随车证（IRP）", pr: "Apportioned Registration Cab Card" },
  { en: "Insurance", cn: "保险", pr: "Insurance" }
];

// ====== 美国各州（English + 中文 + 读音提示） ======
const statesData = [
  { en: "Alabama", cn: "阿拉巴马州", pr: "Alabama" },
  { en: "Alaska", cn: "阿拉斯加州", pr: "Alaska" },
  { en: "Arizona", cn: "亚利桑那州", pr: "Arizona" },
  { en: "Arkansas", cn: "阿肯色州", pr: "Arkansas" },
  { en: "California", cn: "加利福尼亚州", pr: "California" },
  { en: "Colorado", cn: "科罗拉多州", pr: "Colorado" },
  { en: "Connecticut", cn: "康涅狄格州", pr: "Connecticut" },
  { en: "Delaware", cn: "特拉华州", pr: "Delaware" },
  { en: "Florida", cn: "佛罗里达州", pr: "Florida" },
  { en: "Georgia", cn: "乔治亚州", pr: "Georgia" },
  { en: "Hawaii", cn: "夏威夷州", pr: "Hawaii" },
  { en: "Idaho", cn: "爱达荷州", pr: "Idaho" },
  { en: "Illinois", cn: "伊利诺伊州", pr: "Illinois" },
  { en: "Indiana", cn: "印第安纳州", pr: "Indiana" },
  { en: "Iowa", cn: "爱荷华州", pr: "Iowa" },
  { en: "Kansas", cn: "堪萨斯州", pr: "Kansas" },
  { en: "Kentucky", cn: "肯塔基州", pr: "Kentucky" },
  { en: "Louisiana", cn: "路易斯安那州", pr: "Louisiana" },
  { en: "Maine", cn: "缅因州", pr: "Maine" },
  { en: "Maryland", cn: "马里兰州", pr: "Maryland" },
  { en: "Massachusetts", cn: "马萨诸塞州", pr: "Massachusetts" },
  { en: "Michigan", cn: "密歇根州", pr: "Michigan" },
  { en: "Minnesota", cn: "明尼苏达州", pr: "Minnesota" },
  { en: "Mississippi", cn: "密西西比州", pr: "Mississippi" },
  { en: "Missouri", cn: "密苏里州", pr: "Missouri" },
  { en: "Montana", cn: "蒙大拿州", pr: "Montana" },
  { en: "Nebraska", cn: "内布拉斯加州", pr: "Nebraska" },
  { en: "Nevada", cn: "内华达州", pr: "Nevada" },
  { en: "New Hampshire", cn: "新罕布什尔州", pr: "New Hampshire" },
  { en: "New Jersey", cn: "新泽西州", pr: "New Jersey" },
  { en: "New Mexico", cn: "新墨西哥州", pr: "New Mexico" },
  { en: "New York", cn: "纽约州", pr: "New York" },
  { en: "North Carolina", cn: "北卡罗来纳州", pr: "North Carolina" },
  { en: "North Dakota", cn: "北达科他州", pr: "North Dakota" },
  { en: "Ohio", cn: "俄亥俄州", pr: "Ohio" },
  { en: "Oklahoma", cn: "俄克拉荷马州", pr: "Oklahoma" },
  { en: "Oregon", cn: "俄勒冈州", pr: "Oregon" },
  { en: "Pennsylvania", cn: "宾夕法尼亚州", pr: "Pennsylvania" },
  { en: "Rhode Island", cn: "罗得岛州", pr: "Rhode Island" },
  { en: "South Carolina", cn: "南卡罗来纳州", pr: "South Carolina" },
  { en: "South Dakota", cn: "南达科他州", pr: "South Dakota" },
  { en: "Tennessee", cn: "田纳西州", pr: "Tennessee" },
  { en: "Texas", cn: "德克萨斯州", pr: "Texas" },
  { en: "Utah", cn: "犹他州", pr: "Utah" },
  { en: "Vermont", cn: "佛蒙特州", pr: "Vermont" },
  { en: "Virginia", cn: "弗吉尼亚州", pr: "Virginia" },
  { en: "Washington", cn: "华盛顿州", pr: "Washington" },
  { en: "West Virginia", cn: "西弗吉尼亚州", pr: "West Virginia" },
  { en: "Wisconsin", cn: "威斯康星州", pr: "Wisconsin" },
  { en: "Wyoming", cn: "怀俄明州", pr: "Wyoming" }
];
